services:
  - type: web
    name: bandy-manager
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
